name: Xcepto .NET release pipeline
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: start services
        run: |
          cd Samples/Shopping && docker compose -f docker-compose.yaml up -d

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: run tests
        run: dotnet test
        env:
          RABBITMQ_URL: localhost

      - name: stop services
        run: |
          cd Samples/Shopping && docker compose -f docker-compose.yaml down
          
          
  release:
    runs-on: ubuntu-latest
    needs: [ tests ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/github @semantic-release/exec

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}