name: Xcepto .NET release pipeline
on:
  push: 
  release:
    types:
      - published

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: start services
        run: |
          cd Samples/Shopping && docker compose -f docker-compose.yaml up -d

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404' 

      - name: run tests
        run: dotnet test dotnet/dotnet.sln
        env:
          RABBITMQ_URL: localhost

      - name: stop services
        run: |
          cd Samples/Shopping && docker compose -f docker-compose.yaml down

  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    if: github.event.action == 'published' || (contains(github.event.inputs.workflow_mode, 'release'))

    strategy:
      matrix:
        project:
          - Xcepto/Xcepto.csproj
          - Xcepto.Rest/Xcepto.Rest.csproj
          - Xcepto.RabbitMQ/Xcepto.RabbitMQ.csproj

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404' 

      - name: Set Version
        id: vars
        run: echo "VERSION=1.0.0-alpha.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore ${{ matrix.project }}

      - name: Build
        run: dotnet build ${{ matrix.project }} --configuration Release --no-restore -p:Version=$VERSION

      - name: Pack
        run: dotnet pack ${{ matrix.project }} --configuration Release --no-build --output ./nupkg -p:Version=$VERSION

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json